
services:
  bot:
    env_file: &env_file .env.example
    build:
      context: .
    working_dir: /opt/bot
    command:
      - uv
      - run
      - python
      - tests/tools/run_bot.py
    depends_on:
      - postgres
    volumes:
      - uv_cache_dir:/root/.cache/uv
      - ${PWD}/.env:/opt/bot/.env

  postgres:
    env_file: *env_file
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  pg_data:
  uv_cache_dir:
