INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (41,1,'searches','searches info support'),
	 (116,74,'searches','searches all'),
	 (120,2,'searches','searches active'),
	 (121,7,'searches','searches active'),
	 (122,23,'searches','searches all'),
	 (123,3,'searches','searches active'),
	 (125,26,'searches','searches active'),
	 (126,25,'searches','searches active'),
	 (131,30,'searches','searches all'),
	 (132,11,'searches','searches active') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (137,41,'searches','searches active'),
	 (138,14,'searches','searches active'),
	 (143,6,'searches','searches active'),
	 (151,18,'searches','searches active'),
	 (153,9,'searches','searches active'),
	 (154,38,'searches','searches active'),
	 (155,22,'searches','searches active'),
	 (157,31,'searches','searches active'),
	 (161,40,'searches','searches all'),
	 (162,10,'searches','searches active') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (163,59,'searches','searches active'),
	 (170,57,'searches','searches active'),
	 (173,63,'searches','searches active'),
	 (177,5,'searches','searches active'),
	 (179,66,'searches','searches all'),
	 (180,67,'searches','searches all'),
	 (181,68,'searches','searches all'),
	 (182,70,'searches','searches all'),
	 (183,72,'searches','searches all'),
	 (184,73,'searches','searches all') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (338,49,'searches','searches active'),
	 (339,48,'searches','searches active'),
	 (368,32,'searches','searches finished'),
	 (369,32,'searches','searches info support'),
	 (370,32,'searches','searches active'),
	 (371,13,'searches','searches active'),
	 (372,13,'searches','searches info support'),
	 (373,13,'searches','searches finished'),
	 (376,33,'searches','searches finished'),
	 (377,33,'searches','searches info support') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (378,33,'searches','searches active'),
	 (382,34,'searches','searches finished'),
	 (383,34,'searches','searches info support'),
	 (384,34,'searches','searches active'),
	 (386,41,'searches','searches active'),
	 (387,41,'searches','searches info support'),
	 (390,39,'searches','searches all'),
	 (391,47,'searches','searches active'),
	 (392,47,'searches','searches finished'),
	 (401,44,'searches','searches finished') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (402,45,'searches','searches all'),
	 (403,75,'searches','searches active'),
	 (404,75,'searches','searches finished'),
	 (406,10,'searches','searches finished'),
	 (411,1,'searches','searches finished'),
	 (412,1,'searches','searches finished'),
	 (53,NULL,'common_info',NULL),
	 (185,17,'searches','searches active'),
	 (186,19,'searches','searches active'),
	 (187,71,'searches','searches all') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (188,69,'searches','searches all'),
	 (191,52,'searches','searches active'),
	 (193,11,'searches','searches finished'),
	 (202,42,'searches','searches active'),
	 (204,51,'searches','searches all'),
	 (210,34,'searches','searches active'),
	 (211,53,'searches','searches active'),
	 (212,58,'searches','searches all'),
	 (213,46,'searches','searches active'),
	 (215,44,'searches','searches active') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (222,21,'searches','searches active'),
	 (231,59,'searches','searches finished'),
	 (233,3,'searches','searches finished'),
	 (235,52,'searches','searches finished'),
	 (236,15,'searches','searches all'),
	 (237,60,'searches','searches active'),
	 (239,60,'searches','searches finished'),
	 (264,27,'searches','searches all'),
	 (265,8,'searches','searches active'),
	 (266,19,'searches','searches finished') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (269,43,'searches','searches active'),
	 (271,16,'searches','searches active'),
	 (272,20,'searches','searches active'),
	 (273,24,'searches','searches active'),
	 (274,36,'searches','searches all'),
	 (275,53,'searches','searches finished'),
	 (276,1,'searches','searches active'),
	 (280,50,'searches','searches all'),
	 (289,7,'searches','searches finished'),
	 (290,61,'searches','searches active') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (291,64,'searches','searches all'),
	 (292,62,'searches','searches all'),
	 (293,12,'searches','searches active'),
	 (294,55,'searches','searches all'),
	 (295,54,'searches','searches active'),
	 (297,54,'searches','searches finished'),
	 (298,37,'searches','searches active'),
	 (299,28,'searches','searches all'),
	 (300,2,'searches','searches finished'),
	 (301,65,'searches','searches all') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (303,41,'searches','searches finished'),
	 (305,4,'searches','searches finished'),
	 (308,42,'searches','searches finished'),
	 (310,5,'searches','searches finished'),
	 (311,18,'searches','searches finished'),
	 (314,9,'searches','searches finished'),
	 (315,16,'searches','searches finished'),
	 (318,43,'searches','searches finished'),
	 (320,61,'searches','searches finished'),
	 (322,57,'searches','searches finished') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (324,21,'searches','searches finished'),
	 (325,6,'searches','searches finished'),
	 (327,8,'searches','searches finished'),
	 (330,35,'searches','searches all'),
	 (333,4,'searches','searches active'),
	 (334,4,'searches','searches info support'),
	 (336,29,'searches','searches all'),
	 (337,56,'searches','searches all'),
	 (48,NULL,'common_info',NULL),
	 (415,1,'searches','searches finished') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (416,22,'searches','searches finished'),
	 (418,26,'searches','searches finished'),
	 (420,24,'searches','searches finished'),
	 (422,76,'searches','searches all'),
	 (423,77,'searches','searches all'),
	 (424,14,'searches','searches finished'),
	 (431,19,'searches','searches info support'),
	 (432,31,'searches','searches finished'),
	 (434,17,'searches','searches finished'),
	 (436,12,'searches','searches finished') ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (441,20,'searches','searches finished'),
	 (444,37,'searches','searches finished'),
	 (447,38,'searches','searches finished'),
	 (449,46,'searches','searches finished'),
	 (451,25,'searches','searches finished'),
	 (453,49,'searches','searches finished'),
	 (455,63,'searches','searches finished'),
	 (456,48,'searches','searches info support'),
	 (457,48,'searches','searches finished'),
	 (84,NULL,'common_info',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (86,NULL,'common_info',NULL),
	 (88,NULL,'common_info',NULL),
	 (89,1,'events',NULL),
	 (90,NULL,'common_info',NULL),
	 (91,NULL,'common_info',NULL),
	 (112,NULL,'common_info',NULL),
	 (113,NULL,'common_info',NULL),
	 (165,NULL,'common_info',NULL),
	 (171,NULL,'common_info',NULL),
	 (172,NULL,'common_info',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (189,NULL,'common_info',NULL),
	 (190,NULL,'common_info',NULL),
	 (192,NULL,'common_info',NULL),
	 (200,NULL,'common_info',NULL),
	 (207,NULL,'archive',NULL),
	 (214,NULL,'common_info',NULL),
	 (232,3,'events',NULL),
	 (238,60,'events',NULL),
	 (268,NULL,'common_info',NULL),
	 (270,NULL,'common_info',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (278,NULL,'archive',NULL),
	 (281,NULL,'archive',NULL),
	 (283,NULL,'archive',NULL),
	 (284,NULL,'archive',NULL),
	 (287,NULL,'archive',NULL),
	 (288,7,'events',NULL),
	 (302,2,'events',NULL),
	 (304,41,'events',NULL),
	 (306,4,'events',NULL),
	 (307,42,'events',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (309,5,'events',NULL),
	 (312,18,'events',NULL),
	 (313,9,'events',NULL),
	 (317,43,'events',NULL),
	 (321,57,'events',NULL),
	 (326,6,'events',NULL),
	 (328,8,'events',NULL),
	 (329,19,'events',NULL),
	 (352,NULL,'archive',NULL),
	 (353,NULL,'archive',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (355,NULL,'archive',NULL),
	 (356,NULL,'archive',NULL),
	 (362,NULL,'archive',NULL),
	 (363,NULL,'archive',NULL),
	 (365,1,'events',NULL),
	 (367,32,'events',NULL),
	 (374,13,'events',NULL),
	 (375,33,'events',NULL),
	 (394,NULL,'archive',NULL),
	 (395,NULL,'archive',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (396,1,'archive',NULL),
	 (397,1,'archive',NULL),
	 (398,NULL,'archive',NULL),
	 (399,NULL,'archive',NULL),
	 (400,44,'events',NULL),
	 (405,75,'events',NULL),
	 (407,NULL,'common_info',NULL),
	 (408,10,'events',NULL),
	 (414,NULL,'archive',NULL),
	 (417,22,'events',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (421,24,'events',NULL),
	 (433,31,'events',NULL),
	 (435,17,'events',NULL),
	 (437,12,'events',NULL),
	 (439,NULL,'archive',NULL),
	 (440,NULL,'archive',NULL),
	 (443,20,'events',NULL),
	 (445,37,'events',NULL),
	 (446,38,'events',NULL),
	 (448,46,'events',NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.geo_folders (folder_id,division_id,folder_type,folder_subtype) VALUES
	 (450,25,'events',NULL),
	 (452,49,'events',NULL),
	 (454,63,'events',NULL),
	 (458,48,'events',NULL),
	 (459,48,'events',NULL) ON CONFLICT DO NOTHING;
