name: 'Deploy to Yandex Cloud Function'
description: 'Deploy Python function to Yandex Cloud Functions with common environment variables'
inputs:
  yc-sa-json-credentials:
    required: true
    description: 'Service account JSON credentials'
  bucket:
    required: true
    description: 'YC S3 bucket name'  
  folder-id:
    required: true
    description: 'YC folder ID'
  function-name:
    required: true
    description: 'Cloud function name'
  runtime:
    required: true
    description: 'Python runtime version'
  memory:
    required: true
    description: 'Memory allocation'
  entrypoint:
    required: true
    description: 'Function entrypoint'
  source-root:
    required: true
    description: 'Path to function source code'

runs:
  using: "composite"
  steps:
    - uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ inputs.yc-sa-json-credentials }}
        bucket: ${{ inputs.bucket }}
        folder-id: ${{ inputs.folder-id }}
        function-name: ${{ inputs.function-name }}
        runtime: ${{ inputs.runtime }}
        memory: ${{ inputs.memory }}
        entrypoint: ${{ inputs.entrypoint }}
        source-root: ${{ inputs.source-root }}
        environment: |
          POSTGRES_HOST=${{ secrets.YC_POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.YC_POSTGRES_PORT }}
          POSTGRES_DB=${{ secrets.YC_POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.YC_POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.YC_POSTGRES_PASSWORD }}
