name: Reusable Google Cloud Function Deployment (V1, Trigger)

on:
  workflow_call:
    inputs:

      function_name:
        required: true
        type: string

      event_trigger_resource:
        required: true
        type: string

      memory:
        required: false
        type: string
        default: 256

      max_instances:
        required: false
        type: string
        default: 1

      timeout:
        required: false
        type: string
        default: 60
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make dependencies
        run: make dependencies

      - name: Authenticate in GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: Deploy the CF
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
            source_dir: src/${{ inputs.function_name }} # name of directory
            labels: gcf=${{ inputs.function_name }}
            name: ${{ inputs.function_name }} # name of deploying function
            runtime: python310
            entry_point: main # UPD HERE! main function
            region: europe-west3
            docker_registry: artifact-registry
            timeout: ${{ inputs.timeout }}
            memory_mb: ${{ inputs.memory }}
            max_instances: ${{ inputs.max_instances }}
            # timeout: 540 # UPD HERE!
            # max_instances: 1 # UPD HERE!
            # memory_mb: 8192 # UPD HERE!
            event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
            event_trigger_resource: ${{ inputs.event_trigger_resource }}
