name: Deploy-VK-Bot

on:
  push:
    branches: [ main ]
    paths:
      - 'src/vk_bot/**'
      - '.github/workflows/deploy_vk_bot.yml'
      - 'src/_dependencies/*'
      - '.github/workflows/_reusable_wf_yc.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_reusable_wf_yc.yml
    secrets: inherit
    with:
      function_name: vk_bot
      
