name: Deploy-Test-Func

on:
  push:
    branches: [ yandex-rebased ]
    paths:
      - 'src/_dependencies/*'
      - 'src/communicate/**' # UPD HERE!
      - '.github/workflows/deploy_yandex_test.yml' # UPD HERE!
      - '.github/workflows/_reusable_wf_yc.yml'

jobs:
  deploy:
    uses: ./.github/workflows/_reusable_wf_yc.yml
    secrets: inherit
    with:
      function_name: 'test_func'
      memory: '128Mb'
