name: Deploy to Yandex Cloud Functions API-Get-Active-Searches

on:
  push:
    branches: [ yandex-rebased ]
    paths:
      - 'src/_dependencies/*'
      - 'src/api_get_active_searches/**' # UPD HERE!
      - '.github/workflows/deploy_api_get_active_searches.yml' # UPD HERE!
      - '.github/workflows/_reusable_wf_yc.yml' # reusable

jobs:
  deploy:
    uses: ./.github/workflows/_reusable_wf_yc.yml
    secrets: inherit
    with:
      function-name: 'api-get-active-searches'
      local-name: 'api_get_active_searches'
      memory: '256MB'
