name: Deploy to Yandex Cloud Functions title_recognize

on:
  push:
    branches: [ yandex-rebased ]
    paths:
      - 'src/_dependencies/*'
      - 'src/title_recognize/**' # UPD HERE!
      - '.github/workflows/deploy_title_recognize.yml' # UPD HERE!
      - '.github/workflows/_reusable_wf_yc.yml' # reusable

jobs:
  deploy:
    uses: ./.github/workflows/_reusable_wf_yc.yml
    secrets: inherit
    with:
      function-name: 'title-recognize'
      local-name: 'title_recognize'
      memory: '384Mb'
